// Built-in SSC CGL style question bank: 25 questions in each of the four sections.
// Every answer was worked out or checked by hand. General Awareness questions also have Hindi.
import 'logic.dart';

const bank = <Question>[
  // ---------------- Quant: Percentages ----------------
  Question(
    id: 1,
    sec: 'quant',
    topic: 'Percentages',
    q: 'If 20% of a number is 70, what is 45% of the same number?',
    o: ['140', '157.5', '150', '162.5'],
    a: 1,
    ex: 'The number is 70 ÷ 0.20 = 350. 45% of 350 = 157.5.',
  ),
  Question(
    id: 2,
    sec: 'quant',
    topic: 'Percentages',
    q: "A's salary is 25% more than B's. By what percentage is B's salary less than A's?",
    o: ['20%', '25%', '22.5%', '18%'],
    a: 0,
    ex: 'If B earns 100, A earns 125. B is 25 less than 125, and 25 ÷ 125 = 20%.',
  ),
  Question(
    id: 3,
    sec: 'quant',
    topic: 'Percentages',
    q: 'A number is increased by 20% and then decreased by 20%. What is the net change?',
    o: ['No change', '4% increase', '4% decrease', '2% decrease'],
    a: 2,
    ex: '1.20 × 0.80 = 0.96, so the number falls by 4%. Shortcut: 20 − 20 − (20 × 20)/100 = −4.',
  ),
  Question(
    id: 4,
    sec: 'quant',
    topic: 'Percentages',
    q: 'A candidate scoring 30% fails by 30 marks. Another scoring 45% gets 15 marks more than the pass mark. What are the maximum marks?',
    o: ['250', '300', '350', '400'],
    a: 1,
    ex: 'The gap between 30% and 45% is 30 + 15 = 45 marks. So 15% = 45 and the maximum is 300.',
  ),
  Question(
    id: 5,
    sec: 'quant',
    topic: 'Percentages',
    q: "A town's population of 50,000 grows by 10% in the first year and 20% in the second. What is it after two years?",
    o: ['65,000', '66,000', '64,000', '67,500'],
    a: 1,
    ex: '50,000 × 1.10 × 1.20 = 66,000.',
  ),
  // ---------------- Quant: Profit and loss ----------------
  Question(
    id: 6,
    sec: 'quant',
    topic: 'Profit and loss',
    q: 'A shopkeeper marks goods 25% above cost and gives a 10% discount. What is his profit percentage?',
    o: ['10%', '12.5%', '15%', '17.5%'],
    a: 1,
    ex: 'Selling price = 1.25 × 0.90 = 1.125 of cost, so profit = 12.5%. Shortcut: 25 − 10 − (25 × 10)/100 = 12.5.',
  ),
  Question(
    id: 7,
    sec: 'quant',
    topic: 'Profit and loss',
    q: 'An article bought for ₹800 is sold for ₹920. What is the profit percentage?',
    o: ['12%', '15%', '13%', '18%'],
    a: 1,
    ex: 'Profit = ₹120. 120 ÷ 800 × 100 = 15%.',
  ),
  Question(
    id: 8,
    sec: 'quant',
    topic: 'Profit and loss',
    q: 'By selling an article for ₹450, a man loses 10%. At what price should he sell it to gain 20%?',
    o: ['₹540', '₹580', '₹600', '₹620'],
    a: 2,
    ex: 'Cost = 450 ÷ 0.90 = ₹500. For a 20% gain, sell at 500 × 1.20 = ₹600.',
  ),
  Question(
    id: 9,
    sec: 'quant',
    topic: 'Profit and loss',
    q: 'A trader sells two articles for ₹1,200 each, gaining 20% on one and losing 20% on the other. What is the overall result?',
    o: ['No profit, no loss', '4% loss', '4% gain', '2% loss'],
    a: 1,
    ex: 'Costs are 1,200 ÷ 1.2 = ₹1,000 and 1,200 ÷ 0.8 = ₹1,500. Total cost ₹2,500, total sale ₹2,400: a loss of 100 ÷ 2,500 = 4%.',
  ),
  Question(
    id: 10,
    sec: 'quant',
    topic: 'Profit and loss',
    q: 'A shopkeeper sells at cost price but uses a 900 g weight instead of 1 kg. What is his gain percentage?',
    o: ['10%', '11.11%', '9.09%', '12.5%'],
    a: 1,
    ex: 'He gives 900 g and charges for 1,000 g. Gain = 100 ÷ 900 × 100 = 11 1/9% ≈ 11.11%.',
  ),
  // ---------------- Quant: Time and work ----------------
  Question(
    id: 11,
    sec: 'quant',
    topic: 'Time and work',
    q: '12 men can finish a job in 15 days. How many days will 20 men take?',
    o: ['8', '9', '10', '12'],
    a: 1,
    ex: 'Work = 12 × 15 = 180 man-days. 180 ÷ 20 = 9 days.',
  ),
  Question(
    id: 12,
    sec: 'quant',
    topic: 'Time and work',
    q: 'A can do a piece of work in 10 days and B in 15 days. How long will they take working together?',
    o: ['5 days', '6 days', '7.5 days', '8 days'],
    a: 1,
    ex: 'Together they do 1/10 + 1/15 = 1/6 of the work a day, so 6 days.',
  ),
  Question(
    id: 13,
    sec: 'quant',
    topic: 'Time and work',
    q: 'A and B together finish a job in 12 days. A alone takes 20 days. How long does B alone take?',
    o: ['24 days', '28 days', '30 days', '32 days'],
    a: 2,
    ex: "B's rate = 1/12 − 1/20 = 2/60 = 1/30, so 30 days.",
  ),
  Question(
    id: 14,
    sec: 'quant',
    topic: 'Time and work',
    q: 'One pipe fills a tank in 6 hours and another empties it in 9 hours. With both open, how long does the empty tank take to fill?',
    o: ['12 hours', '15 hours', '18 hours', '24 hours'],
    a: 2,
    ex: 'Net rate = 1/6 − 1/9 = 1/18 of the tank an hour, so 18 hours.',
  ),
  Question(
    id: 15,
    sec: 'quant',
    topic: 'Time and work',
    q: 'A can finish a job in 18 days. He works for 6 days, and B finishes the rest in 8 days. How long would B take alone?',
    o: ['10 days', '12 days', '14 days', '16 days'],
    a: 1,
    ex: 'In 6 days A does 6/18 = 1/3. B does the remaining 2/3 in 8 days, so the whole job in 12 days.',
  ),
  // ---------------- Quant: Geometry ----------------
  Question(
    id: 16,
    sec: 'quant',
    topic: 'Geometry',
    q: 'What is each interior angle of a regular hexagon?',
    o: ['108°', '120°', '135°', '144°'],
    a: 1,
    ex: 'Sum of interior angles = (6 − 2) × 180° = 720°. 720 ÷ 6 = 120°.',
  ),
  Question(
    id: 17,
    sec: 'quant',
    topic: 'Geometry',
    q: 'The hypotenuse of a right triangle is 13 cm and one side is 5 cm. What is its area?',
    o: ['30 cm²', '32.5 cm²', '60 cm²', '65 cm²'],
    a: 0,
    ex: 'The other side is √(169 − 25) = 12 cm. Area = ½ × 5 × 12 = 30 cm².',
  ),
  Question(
    id: 18,
    sec: 'quant',
    topic: 'Geometry',
    q: 'Two angles of a triangle are 65° and 45°. What is the third angle?',
    o: ['60°', '70°', '80°', '90°'],
    a: 1,
    ex: '180° − 65° − 45° = 70°.',
  ),
  Question(
    id: 19,
    sec: 'quant',
    topic: 'Geometry',
    q: 'The area of a circle is 154 cm². What is its circumference? (Take π = 22/7)',
    o: ['22 cm', '44 cm', '66 cm', '88 cm'],
    a: 1,
    ex: 'r² = 154 × 7/22 = 49, so r = 7 cm. Circumference = 2 × 22/7 × 7 = 44 cm.',
  ),
  Question(
    id: 20,
    sec: 'quant',
    topic: 'Geometry',
    q: 'The diagonal of a square is 10√2 cm. What is its area?',
    o: ['50 cm²', '100 cm²', '200 cm²', '100√2 cm²'],
    a: 1,
    ex: 'Side = diagonal ÷ √2 = 10 cm, so the area is 100 cm². (Or area = diagonal² ÷ 2 = 200 ÷ 2.)',
  ),
  // ---------------- Quant: Data interpretation ----------------
  Question(
    id: 21,
    sec: 'quant',
    topic: 'Data interpretation',
    q: "A shop's sales (₹ lakh) were 40 in 2022, 50 in 2023 and 60 in 2024. What was the growth from 2023 to 2024?",
    o: ['10%', '20%', '25%', '50%'],
    a: 1,
    ex: 'Growth = (60 − 50) ÷ 50 × 100 = 20%. Take the earlier year as the base.',
  ),
  Question(
    id: 22,
    sec: 'quant',
    topic: 'Data interpretation',
    q: 'Five students scored 45, 52, 60, 38 and 55. What is their average score?',
    o: ['48', '50', '52', '54'],
    a: 1,
    ex: 'Total = 250. 250 ÷ 5 = 50.',
  ),
  Question(
    id: 23,
    sec: 'quant',
    topic: 'Data interpretation',
    q: 'In a class of 60, a pie chart gives Cricket 25% and Football 40%. The rest prefer Hockey. How many prefer Hockey?',
    o: ['15', '18', '21', '24'],
    a: 2,
    ex: 'Hockey = 100 − 25 − 40 = 35%. 35% of 60 = 21.',
  ),
  Question(
    id: 24,
    sec: 'quant',
    topic: 'Data interpretation',
    q: 'A factory produced 120 tonnes in January, 150 in February and 90 in March. What is the ratio of February to March production?',
    o: ['3 : 5', '5 : 3', '4 : 3', '5 : 4'],
    a: 1,
    ex: '150 : 90 = 5 : 3 (divide both by 30).',
  ),
  Question(
    id: 25,
    sec: 'quant',
    topic: 'Data interpretation',
    q: 'A pie chart shows a monthly budget of ₹40,000. Rent takes a 72° sector. How much is the rent?',
    o: ['₹7,200', '₹8,000', '₹9,000', '₹10,000'],
    a: 1,
    ex: '72° is 72/360 = 1/5 of the circle. 40,000 ÷ 5 = ₹8,000.',
  ),

  // ---------------- Reasoning: Series ----------------
  Question(
    id: 26,
    sec: 'reason',
    topic: 'Series',
    q: 'Find the next number: 3, 8, 15, 24, 35, ?',
    o: ['46', '47', '48', '49'],
    a: 2,
    ex: 'Differences are 5, 7, 9, 11, so the next is 13. 35 + 13 = 48. (Also n² − 1 for n = 2…7.)',
  ),
  Question(
    id: 27,
    sec: 'reason',
    topic: 'Series',
    q: 'Find the next number: 2, 6, 12, 20, 30, ?',
    o: ['36', '40', '42', '44'],
    a: 2,
    ex: 'Differences are 4, 6, 8, 10, so the next is 12. 30 + 12 = 42. (Also n × (n + 1).)',
  ),
  Question(
    id: 28,
    sec: 'reason',
    topic: 'Series',
    q: 'Find the next number: 5, 10, 20, 40, ?',
    o: ['60', '70', '80', '100'],
    a: 2,
    ex: 'Each term doubles. 40 × 2 = 80.',
  ),
  Question(
    id: 29,
    sec: 'reason',
    topic: 'Series',
    q: 'Find the next number: 1, 4, 9, 16, 25, ?',
    o: ['30', '35', '36', '49'],
    a: 2,
    ex: 'These are squares of 1 to 5. The next is 6² = 36.',
  ),
  Question(
    id: 30,
    sec: 'reason',
    topic: 'Series',
    q: 'Find the next letter: A, C, F, J, O, ?',
    o: ['S', 'T', 'U', 'V'],
    a: 2,
    ex: 'The gaps are +2, +3, +4, +5, so the next is +6. O is the 15th letter; the 21st is U.',
  ),
  Question(
    id: 31,
    sec: 'reason',
    topic: 'Series',
    q: 'Find the next number: 7, 11, 13, 17, 19, ?',
    o: ['21', '22', '23', '25'],
    a: 2,
    ex: 'These are consecutive prime numbers. The prime after 19 is 23.',
  ),
  Question(
    id: 32,
    sec: 'reason',
    topic: 'Series',
    q: 'Find the next number: 3, 6, 18, 72, ?',
    o: ['144', '216', '288', '360'],
    a: 3,
    ex: 'Multiply by 2, 3, 4, then 5. 72 × 5 = 360.',
  ),
  // ---------------- Reasoning: Coding-decoding ----------------
  Question(
    id: 33,
    sec: 'reason',
    topic: 'Coding-decoding',
    q: 'If CAT is coded as DBU, how is DOG coded?',
    o: ['EPH', 'EOG', 'DPH', 'FQI'],
    a: 0,
    ex: 'Each letter moves one place forward: D→E, O→P, G→H.',
  ),
  Question(
    id: 34,
    sec: 'reason',
    topic: 'Coding-decoding',
    q: 'If PEN is written as 16-5-14, how is INK written?',
    o: ['9-14-11', '9-13-11', '8-14-11', '9-14-12'],
    a: 0,
    ex: 'Each letter is replaced by its position in the alphabet: I = 9, N = 14, K = 11.',
  ),
  Question(
    id: 35,
    sec: 'reason',
    topic: 'Coding-decoding',
    q: 'If MANGO is written as OCPIQ, how is APPLE written?',
    o: ['CRRNG', 'CQQNG', 'BRRMF', 'CRRMG'],
    a: 0,
    ex: 'Each letter moves two places forward: A→C, P→R, P→R, L→N, E→G.',
  ),
  Question(
    id: 36,
    sec: 'reason',
    topic: 'Coding-decoding',
    q: 'If ROSE is coded as ESOR, how is LILY coded?',
    o: ['YLIL', 'LILY', 'YLLI', 'ILYL'],
    a: 0,
    ex: 'The word is written in reverse. LILY backwards is YLIL.',
  ),
  Question(
    id: 37,
    sec: 'reason',
    topic: 'Coding-decoding',
    q: "If 'sky' is called 'sea', 'sea' is called 'water' and 'water' is called 'air', where do fish live?",
    o: ['sea', 'water', 'air', 'sky'],
    a: 2,
    ex: "Fish live in water, and in this code water is called 'air'.",
  ),
  Question(
    id: 38,
    sec: 'reason',
    topic: 'Coding-decoding',
    q: 'If each letter is replaced by its opposite letter (A↔Z, B↔Y and so on), how is GOLD written?',
    o: ['TLOW', 'TLOX', 'SLOW', 'TMOW'],
    a: 0,
    ex: 'Opposite letters add up to 27: G(7)→T(20), O(15)→L(12), L(12)→O(15), D(4)→W(23).',
  ),
  // ---------------- Reasoning: Syllogism ----------------
  Question(
    id: 39,
    sec: 'reason',
    topic: 'Syllogism',
    q: 'Statements: All pens are books. All books are chairs.\nConclusions: I. All pens are chairs. II. Some chairs are pens.',
    o: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'],
    a: 2,
    ex: 'Pens sit inside books, which sit inside chairs, so all pens are chairs (I). That also means some chairs are pens (II).',
  ),
  Question(
    id: 40,
    sec: 'reason',
    topic: 'Syllogism',
    q: 'Statements: Some cats are dogs. No dog is a rat.\nConclusions: I. Some cats are not rats. II. No cat is a rat.',
    o: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'],
    a: 0,
    ex: 'The cats that are dogs cannot be rats, so I follows. Other cats could still be rats, so II does not.',
  ),
  Question(
    id: 41,
    sec: 'reason',
    topic: 'Syllogism',
    q: 'Statements: All roses are flowers. Some flowers are red.\nConclusions: I. Some roses are red. II. All flowers are roses.',
    o: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'],
    a: 3,
    ex: 'The red flowers may not include any roses, so I does not follow. Roses are only part of flowers, so II does not follow.',
  ),
  Question(
    id: 42,
    sec: 'reason',
    topic: 'Syllogism',
    q: 'Statements: No man is a tree. All trees are green.\nConclusions: I. No man is green. II. Some green things are not men.',
    o: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'],
    a: 1,
    ex: 'Trees are green things that are not men, so II follows. Nothing stops a man from being green, so I does not.',
  ),
  Question(
    id: 43,
    sec: 'reason',
    topic: 'Syllogism',
    q: 'Statements: All teachers are graduates. Some graduates are players.\nConclusions: I. Some teachers are players. II. Some players are graduates.',
    o: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'],
    a: 1,
    ex: '"Some graduates are players" can be reversed to "some players are graduates" (II). The players may not be teachers, so I does not follow.',
  ),
  Question(
    id: 44,
    sec: 'reason',
    topic: 'Syllogism',
    q: 'Statements: All doctors are educated. Some doctors are women.\nConclusions: I. Some women are educated. II. Some educated people are doctors.',
    o: ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'],
    a: 2,
    ex: 'The women who are doctors are educated (I). Since all doctors are educated, some educated people are doctors (II).',
  ),
  // ---------------- Reasoning: Blood relations ----------------
  Question(
    id: 45,
    sec: 'reason',
    topic: 'Blood relations',
    q: "Pointing to a man, Ritu says, \"He is the son of my grandfather's only son.\" How is the man related to Ritu?",
    o: ['Brother', 'Cousin', 'Uncle', 'Father'],
    a: 0,
    ex: "Her grandfather's only son is her father. Her father's son is her brother.",
  ),
  Question(
    id: 46,
    sec: 'reason',
    topic: 'Blood relations',
    q: "A is B's sister. C is B's mother. D is C's father. How is A related to D?",
    o: ['Granddaughter', 'Daughter', 'Grandmother', 'Niece'],
    a: 0,
    ex: "D is the father of A's mother, so D is A's grandfather. A is female, so she is his granddaughter.",
  ),
  Question(
    id: 47,
    sec: 'reason',
    topic: 'Blood relations',
    q: 'Introducing a woman, Raj says, "Her mother is the only daughter of my mother." How is the woman related to Raj?',
    o: ['Niece', 'Sister', 'Daughter', 'Cousin'],
    a: 0,
    ex: "The only daughter of Raj's mother is Raj's sister. Her daughter is Raj's niece.",
  ),
  Question(
    id: 48,
    sec: 'reason',
    topic: 'Blood relations',
    q: 'P is the brother of Q. Q is the daughter of R. R is the wife of S. How is P related to S?',
    o: ['Son', 'Brother', 'Nephew', 'Father'],
    a: 0,
    ex: 'Q is the daughter of R and S. P is her brother, so P is the son of S.',
  ),
  Question(
    id: 49,
    sec: 'reason',
    topic: 'Blood relations',
    q: "Y is the sister of X's father. How is Y related to X?",
    o: ['Aunt', 'Mother', 'Sister', 'Cousin'],
    a: 0,
    ex: "Your father's sister is your aunt (bua).",
  ),
  Question(
    id: 50,
    sec: 'reason',
    topic: 'Blood relations',
    q: "Meena's husband's father is Suresh. Suresh has only one son, Ravi. How is Ravi related to Meena?",
    o: ['Husband', 'Brother-in-law', 'Father-in-law', 'Son'],
    a: 0,
    ex: "Meena's husband is a son of Suresh, and Suresh's only son is Ravi. So Ravi is her husband.",
  ),

  // ---------------- English: Synonyms ----------------
  Question(
    id: 51,
    sec: 'eng',
    topic: 'Synonyms',
    q: 'Choose the word closest in meaning to CANDID.',
    o: ['Frank', 'Secretive', 'Rude', 'Timid'],
    a: 0,
    ex: 'Candid means open and honest, so "frank". "Secretive" is its opposite.',
  ),
  Question(
    id: 52,
    sec: 'eng',
    topic: 'Synonyms',
    q: 'Choose the word closest in meaning to ABUNDANT.',
    o: ['Scarce', 'Plentiful', 'Rare', 'Tiny'],
    a: 1,
    ex: 'Abundant means existing in large quantities: plentiful. "Scarce" and "rare" are opposites.',
  ),
  Question(
    id: 53,
    sec: 'eng',
    topic: 'Synonyms',
    q: 'Choose the word closest in meaning to BENEVOLENT.',
    o: ['Cruel', 'Kind', 'Greedy', 'Lazy'],
    a: 1,
    ex: 'Benevolent means well-meaning and kind. Its opposite is malevolent.',
  ),
  Question(
    id: 54,
    sec: 'eng',
    topic: 'Synonyms',
    q: 'Choose the word closest in meaning to OBSOLETE.',
    o: ['Modern', 'Outdated', 'Useful', 'Rare'],
    a: 1,
    ex: 'Obsolete means no longer used or out of date.',
  ),
  Question(
    id: 55,
    sec: 'eng',
    topic: 'Synonyms',
    q: 'Choose the word closest in meaning to METICULOUS.',
    o: ['Careless', 'Very careful', 'Quick', 'Lucky'],
    a: 1,
    ex: 'Meticulous means showing great attention to detail: very careful.',
  ),
  Question(
    id: 56,
    sec: 'eng',
    topic: 'Synonyms',
    q: 'Choose the word closest in meaning to ADVERSITY.',
    o: ['Prosperity', 'Hardship', 'Enmity', 'Happiness'],
    a: 1,
    ex: 'Adversity means difficulty or misfortune: hardship. "Prosperity" is its opposite.',
  ),
  Question(
    id: 57,
    sec: 'eng',
    topic: 'Synonyms',
    q: 'Choose the word closest in meaning to LUCID.',
    o: ['Clear', 'Confusing', 'Lazy', 'Heavy'],
    a: 0,
    ex: 'Lucid means clear and easy to understand, as in "a lucid explanation".',
  ),
  // ---------------- English: Error spotting ----------------
  Question(
    id: 58,
    sec: 'eng',
    topic: 'Error spotting',
    q: 'Find the part with an error: "One of my friend / has gone / to Mumbai for a job."',
    o: ['One of my friend', 'has gone', 'to Mumbai for a job', 'No error'],
    a: 0,
    ex: '"One of" is followed by a plural noun: "One of my friends".',
  ),
  Question(
    id: 59,
    sec: 'eng',
    topic: 'Error spotting',
    q: 'Find the part with an error: "Neither the teacher / nor the students / was present in the hall."',
    o: ['Neither the teacher', 'nor the students', 'was present in the hall', 'No error'],
    a: 2,
    ex: 'With "neither…nor", the verb agrees with the nearer subject. "Students" is plural, so "were present".',
  ),
  Question(
    id: 60,
    sec: 'eng',
    topic: 'Error spotting',
    q: 'Find the part with an error: "She is / more taller / than her sister."',
    o: ['She is', 'more taller', 'than her sister', 'No error'],
    a: 1,
    ex: '"Taller" is already comparative, so "more" is wrong. Say "She is taller than her sister."',
  ),
  Question(
    id: 61,
    sec: 'eng',
    topic: 'Error spotting',
    q: 'Find the part with an error: "I have been living / in Delhi / since five years."',
    o: ['I have been living', 'in Delhi', 'since five years', 'No error'],
    a: 2,
    ex: 'Use "for" with a length of time and "since" with a point in time: "for five years" or "since 2021".',
  ),
  Question(
    id: 62,
    sec: 'eng',
    topic: 'Error spotting',
    q: 'Find the part with an error: "The news / are very good / today."',
    o: ['The news', 'are very good', 'today', 'No error'],
    a: 1,
    ex: '"News" is an uncountable noun and takes a singular verb: "The news is very good today."',
  ),
  Question(
    id: 63,
    sec: 'eng',
    topic: 'Error spotting',
    q: 'Find the part with an error: "He has been working here / for ten years / and knows everyone."',
    o: ['He has been working here', 'for ten years', 'and knows everyone', 'No error'],
    a: 3,
    ex: 'The sentence is correct: "has been working" with "for ten years", and "knows" agrees with "he".',
  ),
  // ---------------- English: Fill in the blanks ----------------
  Question(
    id: 64,
    sec: 'eng',
    topic: 'Fill in the blanks',
    q: 'She is good ___ mathematics.',
    o: ['in', 'at', 'on', 'with'],
    a: 1,
    ex: 'We say "good at" a subject or skill.',
  ),
  Question(
    id: 65,
    sec: 'eng',
    topic: 'Fill in the blanks',
    q: 'He has been ill ___ Monday.',
    o: ['for', 'since', 'from', 'by'],
    a: 1,
    ex: 'Monday is a point in time, so use "since" with the present perfect.',
  ),
  Question(
    id: 66,
    sec: 'eng',
    topic: 'Fill in the blanks',
    q: 'If I ___ you, I would accept the offer.',
    o: ['am', 'was', 'were', 'be'],
    a: 2,
    ex: 'Imaginary conditions use "were" for every subject in formal English: "If I were you".',
  ),
  Question(
    id: 67,
    sec: 'eng',
    topic: 'Fill in the blanks',
    q: 'The train had left before we ___ the station.',
    o: ['reach', 'reached', 'had reached', 'have reached'],
    a: 1,
    ex: 'The earlier action takes the past perfect ("had left"); the later one takes the simple past ("reached").',
  ),
  Question(
    id: 68,
    sec: 'eng',
    topic: 'Fill in the blanks',
    q: 'Neither of the two answers ___ correct.',
    o: ['are', 'is', 'were', 'have'],
    a: 1,
    ex: '"Neither of" takes a singular verb: "Neither of the answers is correct."',
  ),
  Question(
    id: 69,
    sec: 'eng',
    topic: 'Fill in the blanks',
    q: 'He prevented me ___ going out.',
    o: ['to', 'from', 'for', 'of'],
    a: 1,
    ex: 'The verb "prevent" is followed by "from": "prevent someone from doing something".',
  ),
  // ---------------- English: Idioms ----------------
  Question(
    id: 70,
    sec: 'eng',
    topic: 'Idioms',
    q: 'What does "to beat around the bush" mean?',
    o: ['To avoid the main point', 'To work very hard', 'To search carefully', 'To waste money'],
    a: 0,
    ex: 'To beat around the bush is to avoid talking directly about the main subject.',
  ),
  Question(
    id: 71,
    sec: 'eng',
    topic: 'Idioms',
    q: 'What does "a piece of cake" mean?',
    o: ['Something very easy', 'A small reward', 'A sweet dish', 'A tiny share'],
    a: 0,
    ex: '"The exam was a piece of cake" means it was very easy.',
  ),
  Question(
    id: 72,
    sec: 'eng',
    topic: 'Idioms',
    q: 'What does "to burn the midnight oil" mean?',
    o: ['To waste resources', 'To study or work late into the night', 'To start a quarrel', 'To cook late'],
    a: 1,
    ex: 'It means working or studying late at night, originally by the light of an oil lamp.',
  ),
  Question(
    id: 73,
    sec: 'eng',
    topic: 'Idioms',
    q: 'What does "to let the cat out of the bag" mean?',
    o: ['To free someone', 'To reveal a secret', 'To create confusion', 'To lose something'],
    a: 1,
    ex: 'To let the cat out of the bag is to reveal a secret, often by accident.',
  ),
  Question(
    id: 74,
    sec: 'eng',
    topic: 'Idioms',
    q: 'What does "once in a blue moon" mean?',
    o: ['Every month', 'Very rarely', 'At night', 'Never'],
    a: 1,
    ex: 'Something that happens once in a blue moon happens very rarely.',
  ),
  Question(
    id: 75,
    sec: 'eng',
    topic: 'Idioms',
    q: 'What does "to turn a deaf ear" mean?',
    o: ['To refuse to listen', 'To listen carefully', 'To become deaf', 'To speak loudly'],
    a: 0,
    ex: 'To turn a deaf ear to something is to ignore it deliberately.',
  ),

  // ---------------- General Awareness: Polity ----------------
  Question(
    id: 76,
    sec: 'ga',
    topic: 'Polity',
    q: 'Which Article of the Indian Constitution abolishes untouchability?',
    o: ['Article 14', 'Article 15', 'Article 17', 'Article 19'],
    a: 2,
    ex: 'Article 17 abolishes untouchability and forbids its practice in any form. Article 14 is equality before law; Article 15 bars discrimination.',
    hi: 'भारतीय संविधान का कौन-सा अनुच्छेद अस्पृश्यता का उन्मूलन करता है?',
    ohi: ['अनुच्छेद 14', 'अनुच्छेद 15', 'अनुच्छेद 17', 'अनुच्छेद 19'],
    exhi: 'अनुच्छेद 17 अस्पृश्यता का अंत करता है। अनुच्छेद 14 विधि के समक्ष समानता और अनुच्छेद 15 भेदभाव का निषेध है।',
  ),
  Question(
    id: 77,
    sec: 'ga',
    topic: 'Polity',
    q: 'The Right to Constitutional Remedies is given in which Article?',
    o: ['Article 21', 'Article 32', 'Article 226', 'Article 368'],
    a: 1,
    ex: 'Article 32 lets citizens go directly to the Supreme Court to enforce Fundamental Rights. Article 226 gives High Courts a similar, wider power.',
    hi: 'संवैधानिक उपचारों का अधिकार किस अनुच्छेद में दिया गया है?',
    ohi: ['अनुच्छेद 21', 'अनुच्छेद 32', 'अनुच्छेद 226', 'अनुच्छेद 368'],
    exhi: 'अनुच्छेद 32 के तहत नागरिक मौलिक अधिकारों के लिए सीधे सर्वोच्च न्यायालय जा सकते हैं। अनुच्छेद 226 उच्च न्यायालयों को ऐसी ही, और व्यापक, शक्ति देता है।',
  ),
  Question(
    id: 78,
    sec: 'ga',
    topic: 'Polity',
    q: 'Article 21A (right to education for ages 6–14) was added by which Amendment?',
    o: ['42nd', '44th', '73rd', '86th'],
    a: 3,
    ex: 'The 86th Amendment Act, 2002 inserted Article 21A. The 42nd (1976) added Fundamental Duties.',
    hi: 'अनुच्छेद 21A (6–14 वर्ष के लिए शिक्षा का अधिकार) किस संशोधन से जोड़ा गया?',
    ohi: ['42वाँ', '44वाँ', '73वाँ', '86वाँ'],
    exhi: '86वें संशोधन अधिनियम, 2002 से अनुच्छेद 21A जोड़ा गया। 42वें संशोधन (1976) से मौलिक कर्तव्य जुड़े।',
  ),
  Question(
    id: 79,
    sec: 'ga',
    topic: 'Polity',
    q: 'Which right was removed from the list of Fundamental Rights by the 44th Amendment?',
    o: ['Right to equality', 'Right to property', 'Right to freedom of religion', 'Right against exploitation'],
    a: 1,
    ex: 'The 44th Amendment (1978) made property a legal right under Article 300A instead of a Fundamental Right.',
    hi: '44वें संशोधन द्वारा कौन-सा अधिकार मौलिक अधिकारों की सूची से हटाया गया?',
    ohi: ['समानता का अधिकार', 'संपत्ति का अधिकार', 'धार्मिक स्वतंत्रता का अधिकार', 'शोषण के विरुद्ध अधिकार'],
    exhi: '44वें संशोधन (1978) ने संपत्ति के अधिकार को अनुच्छेद 300A के तहत कानूनी अधिकार बना दिया।',
  ),
  Question(
    id: 80,
    sec: 'ga',
    topic: 'Polity',
    q: 'Who is the ex-officio Chairman of the Rajya Sabha?',
    o: ['The President', 'The Vice-President', 'The Prime Minister', 'The Speaker of the Lok Sabha'],
    a: 1,
    ex: 'Under Article 64, the Vice-President of India is the ex-officio Chairman of the Rajya Sabha.',
    hi: 'राज्यसभा का पदेन सभापति कौन होता है?',
    ohi: ['राष्ट्रपति', 'उपराष्ट्रपति', 'प्रधानमंत्री', 'लोकसभा अध्यक्ष'],
    exhi: 'अनुच्छेद 64 के अनुसार भारत का उपराष्ट्रपति राज्यसभा का पदेन सभापति होता है।',
  ),
  Question(
    id: 81,
    sec: 'ga',
    topic: 'Polity',
    q: 'What is the minimum age to become a member of the Lok Sabha?',
    o: ['18 years', '21 years', '25 years', '30 years'],
    a: 2,
    ex: 'Article 84 sets a minimum age of 25 years for the Lok Sabha and 30 years for the Rajya Sabha.',
    hi: 'लोकसभा का सदस्य बनने के लिए न्यूनतम आयु कितनी है?',
    ohi: ['18 वर्ष', '21 वर्ष', '25 वर्ष', '30 वर्ष'],
    exhi: 'अनुच्छेद 84 के अनुसार लोकसभा के लिए न्यूनतम आयु 25 वर्ष और राज्यसभा के लिए 30 वर्ष है।',
  ),
  // ---------------- General Awareness: History ----------------
  Question(
    id: 82,
    sec: 'ga',
    topic: 'History',
    q: 'In which year was the Battle of Plassey fought?',
    o: ['1757', '1761', '1764', '1857'],
    a: 0,
    ex: "In 1757 Robert Clive's forces defeated Siraj-ud-Daulah, the Nawab of Bengal. The Battle of Buxar was in 1764.",
    hi: 'प्लासी का युद्ध किस वर्ष लड़ा गया था?',
    ohi: ['1757', '1761', '1764', '1857'],
    exhi: '1757 में रॉबर्ट क्लाइव की सेना ने बंगाल के नवाब सिराजुद्दौला को हराया। बक्सर का युद्ध 1764 में हुआ था।',
  ),
  Question(
    id: 83,
    sec: 'ga',
    topic: 'History',
    q: 'Who founded the Maurya Empire?',
    o: ['Ashoka', 'Chandragupta Maurya', 'Bindusara', 'Samudragupta'],
    a: 1,
    ex: 'Chandragupta Maurya founded the empire around 321 BCE with the help of Chanakya. Samudragupta belonged to the Gupta dynasty.',
    hi: 'मौर्य साम्राज्य की स्थापना किसने की?',
    ohi: ['अशोक', 'चंद्रगुप्त मौर्य', 'बिंदुसार', 'समुद्रगुप्त'],
    exhi: 'चंद्रगुप्त मौर्य ने चाणक्य की सहायता से लगभग 321 ईसा पूर्व में इसकी स्थापना की। समुद्रगुप्त गुप्त वंश के थे।',
  ),
  Question(
    id: 84,
    sec: 'ga',
    topic: 'History',
    q: 'In which year did the Jallianwala Bagh massacre take place?',
    o: ['1905', '1915', '1919', '1922'],
    a: 2,
    ex: 'It took place in Amritsar on 13 April 1919, when troops under General Dyer fired on a peaceful gathering.',
    hi: 'जलियांवाला बाग हत्याकांड किस वर्ष हुआ?',
    ohi: ['1905', '1915', '1919', '1922'],
    exhi: '13 अप्रैल 1919 को अमृतसर में जनरल डायर के आदेश पर एक शांतिपूर्ण सभा पर गोलियाँ चलाई गईं।',
  ),
  Question(
    id: 85,
    sec: 'ga',
    topic: 'History',
    q: 'Who gave the slogan "Do or Die" during the Quit India Movement?',
    o: ['Subhas Chandra Bose', 'Mahatma Gandhi', 'Bhagat Singh', 'Jawaharlal Nehru'],
    a: 1,
    ex: 'Gandhi gave the call in Bombay (now Mumbai) on 8 August 1942, when the Quit India resolution was passed.',
    hi: 'भारत छोड़ो आंदोलन के दौरान "करो या मरो" का नारा किसने दिया?',
    ohi: ['सुभाष चंद्र बोस', 'महात्मा गांधी', 'भगत सिंह', 'जवाहरलाल नेहरू'],
    exhi: 'गांधीजी ने 8 अगस्त 1942 को बंबई (अब मुंबई) में भारत छोड़ो प्रस्ताव पारित होने पर यह नारा दिया।',
  ),
  Question(
    id: 86,
    sec: 'ga',
    topic: 'History',
    q: 'In which year was the Indian National Congress founded?',
    o: ['1857', '1885', '1905', '1920'],
    a: 1,
    ex: 'It was founded in 1885, with A. O. Hume among its founders. Its first session was held in Bombay under W. C. Bonnerjee.',
    hi: 'भारतीय राष्ट्रीय कांग्रेस की स्थापना किस वर्ष हुई?',
    ohi: ['1857', '1885', '1905', '1920'],
    exhi: 'इसकी स्थापना 1885 में हुई और ए. ओ. ह्यूम इसके संस्थापकों में थे। पहला अधिवेशन बंबई में डब्ल्यू. सी. बनर्जी की अध्यक्षता में हुआ।',
  ),
  // ---------------- General Awareness: Geography ----------------
  Question(
    id: 87,
    sec: 'ga',
    topic: 'Geography',
    q: 'The Tropic of Cancer does NOT pass through which state?',
    o: ['Rajasthan', 'Odisha', 'Tripura', 'Mizoram'],
    a: 1,
    ex: 'It passes through Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram, not Odisha.',
    hi: 'कर्क रेखा किस राज्य से होकर नहीं गुजरती?',
    ohi: ['राजस्थान', 'ओडिशा', 'त्रिपुरा', 'मिज़ोरम'],
    exhi: 'यह गुजरात, राजस्थान, मध्य प्रदेश, छत्तीसगढ़, झारखंड, पश्चिम बंगाल, त्रिपुरा और मिज़ोरम से गुजरती है, ओडिशा से नहीं।',
  ),
  Question(
    id: 88,
    sec: 'ga',
    topic: 'Geography',
    q: 'Which river is known as the "Dakshin Ganga" (Ganga of the South)?',
    o: ['Krishna', 'Godavari', 'Kaveri', 'Narmada'],
    a: 1,
    ex: 'The Godavari is the longest river of peninsular India, which is why it is called the Dakshin Ganga.',
    hi: 'किस नदी को "दक्षिण गंगा" कहा जाता है?',
    ohi: ['कृष्णा', 'गोदावरी', 'कावेरी', 'नर्मदा'],
    exhi: 'गोदावरी प्रायद्वीपीय भारत की सबसे लंबी नदी है, इसलिए इसे दक्षिण गंगा कहते हैं।',
  ),
  Question(
    id: 89,
    sec: 'ga',
    topic: 'Geography',
    q: 'Which is the largest state of India by area?',
    o: ['Madhya Pradesh', 'Rajasthan', 'Maharashtra', 'Uttar Pradesh'],
    a: 1,
    ex: 'Rajasthan is the largest, followed by Madhya Pradesh and Maharashtra. Uttar Pradesh has the largest population.',
    hi: 'क्षेत्रफल की दृष्टि से भारत का सबसे बड़ा राज्य कौन-सा है?',
    ohi: ['मध्य प्रदेश', 'राजस्थान', 'महाराष्ट्र', 'उत्तर प्रदेश'],
    exhi: 'राजस्थान सबसे बड़ा है, उसके बाद मध्य प्रदेश और महाराष्ट्र हैं। जनसंख्या में उत्तर प्रदेश सबसे बड़ा है।',
  ),
  Question(
    id: 90,
    sec: 'ga',
    topic: 'Geography',
    q: 'The Palk Strait separates India from which country?',
    o: ['Maldives', 'Sri Lanka', 'Myanmar', 'Bangladesh'],
    a: 1,
    ex: 'The Palk Strait lies between Tamil Nadu and the northern tip of Sri Lanka.',
    hi: 'पाक जलडमरूमध्य भारत को किस देश से अलग करता है?',
    ohi: ['मालदीव', 'श्रीलंका', 'म्यांमार', 'बांग्लादेश'],
    exhi: 'पाक जलडमरूमध्य तमिलनाडु और श्रीलंका के उत्तरी सिरे के बीच स्थित है।',
  ),
  Question(
    id: 91,
    sec: 'ga',
    topic: 'Geography',
    q: 'Which of these is a cold desert in India?',
    o: ['Thar', 'Ladakh', 'Rann of Kutch', 'Sundarbans'],
    a: 1,
    ex: 'Ladakh, in the rain shadow of the Himalayas, is a cold desert. The Thar is a hot desert.',
    hi: 'इनमें से कौन-सा भारत का शीत मरुस्थल है?',
    ohi: ['थार', 'लद्दाख', 'कच्छ का रण', 'सुंदरबन'],
    exhi: 'हिमालय के वृष्टि-छाया क्षेत्र में स्थित लद्दाख एक शीत मरुस्थल है। थार एक गर्म मरुस्थल है।',
  ),
  // ---------------- General Awareness: Economy ----------------
  Question(
    id: 92,
    sec: 'ga',
    topic: 'Economy',
    q: 'Where is the headquarters of the Reserve Bank of India?',
    o: ['New Delhi', 'Mumbai', 'Kolkata', 'Chennai'],
    a: 1,
    ex: "The RBI's central office is in Mumbai. It moved there from Kolkata in 1937.",
    hi: 'भारतीय रिज़र्व बैंक का मुख्यालय कहाँ है?',
    ohi: ['नई दिल्ली', 'मुंबई', 'कोलकाता', 'चेन्नई'],
    exhi: 'RBI का केंद्रीय कार्यालय मुंबई में है। यह 1937 में कोलकाता से मुंबई आया।',
  ),
  Question(
    id: 93,
    sec: 'ga',
    topic: 'Economy',
    q: 'When was the Goods and Services Tax (GST) introduced in India?',
    o: ['1 April 2017', '1 July 2017', '1 January 2018', '1 July 2016'],
    a: 1,
    ex: 'GST came into force on 1 July 2017, after the 101st Constitutional Amendment Act, 2016.',
    hi: 'भारत में वस्तु एवं सेवा कर (GST) कब लागू किया गया?',
    ohi: ['1 अप्रैल 2017', '1 जुलाई 2017', '1 जनवरी 2018', '1 जुलाई 2016'],
    exhi: 'GST 101वें संविधान संशोधन अधिनियम, 2016 के बाद 1 जुलाई 2017 से लागू हुआ।',
  ),
  Question(
    id: 94,
    sec: 'ga',
    topic: 'Economy',
    q: 'NITI Aayog replaced which body in 2015?',
    o: ['Finance Commission', 'Planning Commission', 'National Development Council', 'Election Commission'],
    a: 1,
    ex: 'NITI Aayog was set up on 1 January 2015 in place of the Planning Commission (1950). The Prime Minister is its chairperson.',
    hi: 'नीति आयोग ने 2015 में किस संस्था का स्थान लिया?',
    ohi: ['वित्त आयोग', 'योजना आयोग', 'राष्ट्रीय विकास परिषद', 'निर्वाचन आयोग'],
    exhi: 'नीति आयोग 1 जनवरी 2015 को योजना आयोग (1950) के स्थान पर बना। प्रधानमंत्री इसके अध्यक्ष हैं।',
  ),
  Question(
    id: 95,
    sec: 'ga',
    topic: 'Economy',
    q: 'Who signs Indian currency notes, other than the ₹1 note?',
    o: ['The Finance Minister', 'The RBI Governor', 'The Finance Secretary', 'The President'],
    a: 1,
    ex: 'Notes are issued by the RBI and signed by its Governor. The ₹1 note is issued by the Government of India and signed by the Finance Secretary.',
    hi: '₹1 के नोट को छोड़कर भारतीय करेंसी नोटों पर किसके हस्ताक्षर होते हैं?',
    ohi: ['वित्त मंत्री', 'RBI गवर्नर', 'वित्त सचिव', 'राष्ट्रपति'],
    exhi: 'नोट RBI जारी करता है और उन पर उसके गवर्नर के हस्ताक्षर होते हैं। ₹1 का नोट भारत सरकार जारी करती है, जिस पर वित्त सचिव के हस्ताक्षर होते हैं।',
  ),
  Question(
    id: 96,
    sec: 'ga',
    topic: 'Economy',
    q: 'The repo rate is the rate at which:',
    o: [
      'The RBI lends to commercial banks',
      'Banks lend to their customers',
      'The RBI borrows from commercial banks',
      'The government borrows from the public',
    ],
    a: 0,
    ex: 'Repo is the rate at which the RBI lends short-term money to banks against government securities. When the RBI borrows from banks, that is the reverse repo rate.',
    hi: 'रेपो दर वह दर है जिस पर:',
    ohi: [
      'RBI वाणिज्यिक बैंकों को ऋण देता है',
      'बैंक अपने ग्राहकों को ऋण देते हैं',
      'RBI वाणिज्यिक बैंकों से उधार लेता है',
      'सरकार जनता से उधार लेती है',
    ],
    exhi: 'रेपो वह दर है जिस पर RBI सरकारी प्रतिभूतियों के बदले बैंकों को अल्पकालिक ऋण देता है। RBI जिस दर पर बैंकों से उधार लेता है, वह रिवर्स रेपो दर है।',
  ),
  // ---------------- General Awareness: Static GK ----------------
  Question(
    id: 97,
    sec: 'ga',
    topic: 'Static GK',
    q: 'What is the national aquatic animal of India?',
    o: ['Ganges river dolphin', 'Blue whale', 'Gharial', 'Otter'],
    a: 0,
    ex: "The Ganges river dolphin, found in the Ganga and Brahmaputra river systems, is India's national aquatic animal.",
    hi: 'भारत का राष्ट्रीय जलीय जीव कौन-सा है?',
    ohi: ['गंगा नदी डॉल्फ़िन', 'ब्लू व्हेल', 'घड़ियाल', 'ऊदबिलाव'],
    exhi: 'गंगा और ब्रह्मपुत्र नदी तंत्र में पाई जाने वाली गंगा नदी डॉल्फ़िन भारत का राष्ट्रीय जलीय जीव है।',
  ),
  Question(
    id: 98,
    sec: 'ga',
    topic: 'Static GK',
    q: 'Bihu is a festival mainly celebrated in which state?',
    o: ['Assam', 'Odisha', 'Kerala', 'Punjab'],
    a: 0,
    ex: "Bihu is Assam's main festival, celebrated three times a year: Bohag (Rongali), Kati (Kongali) and Magh (Bhogali).",
    hi: 'बिहू मुख्य रूप से किस राज्य का त्योहार है?',
    ohi: ['असम', 'ओडिशा', 'केरल', 'पंजाब'],
    exhi: 'बिहू असम का प्रमुख त्योहार है, जो साल में तीन बार मनाया जाता है: बोहाग (रोंगाली), काति (कोंगाली) और माघ (भोगाली)।',
  ),
  Question(
    id: 99,
    sec: 'ga',
    topic: 'Static GK',
    q: 'Kaziranga National Park is best known for which animal?',
    o: ['Asiatic lion', 'One-horned rhinoceros', 'Snow leopard', 'Nilgiri tahr'],
    a: 1,
    ex: "Kaziranga, in Assam, has the world's largest population of the greater one-horned rhinoceros. Asiatic lions live in Gir, Gujarat.",
    hi: 'काज़ीरंगा राष्ट्रीय उद्यान किस जीव के लिए सबसे अधिक प्रसिद्ध है?',
    ohi: ['एशियाई शेर', 'एक सींग वाला गैंडा', 'हिम तेंदुआ', 'नीलगिरि तहर'],
    exhi: 'असम के काज़ीरंगा में दुनिया में एक सींग वाले गैंडों की सबसे बड़ी आबादी है। एशियाई शेर गुजरात के गिर में पाए जाते हैं।',
  ),
  Question(
    id: 100,
    sec: 'ga',
    topic: 'Static GK',
    q: 'Who wrote India\'s national anthem, "Jana Gana Mana"?',
    o: ['Bankim Chandra Chattopadhyay', 'Rabindranath Tagore', 'Sarojini Naidu', 'Muhammad Iqbal'],
    a: 1,
    ex: "Rabindranath Tagore wrote it in Bengali. Bankim Chandra wrote the national song \"Vande Mataram\", and Iqbal wrote \"Saare Jahan Se Achha\".",
    hi: 'भारत का राष्ट्रगान "जन गण मन" किसने लिखा?',
    ohi: ['बंकिम चंद्र चट्टोपाध्याय', 'रवींद्रनाथ टैगोर', 'सरोजिनी नायडू', 'मुहम्मद इक़बाल'],
    exhi: 'रवींद्रनाथ टैगोर ने इसे बांग्ला में लिखा। बंकिम चंद्र ने राष्ट्रगीत "वंदे मातरम्" और इक़बाल ने "सारे जहाँ से अच्छा" लिखा।',
  ),
];
